/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bennyhuo_jni_JniMain */

#ifndef _Included_com_bennyhuo_jni_JniMain
#define _Included_com_bennyhuo_jni_JniMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bennyhuo_jni_JniMain
 * Method:    fibonacci
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_bennyhuo_jni_JniMain_fibonacci
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
